name: Deploy to Azure Blob Storage

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Azure Blob Storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
          echo "Deploying to Azure Blob Storage"
          az storage blob sync \
            --account-name HASSAN_I \
            --account-key ${{ secrets.HASSAN_I_STORAGE_ACCOUNT_KEY }} \
            --container \$web \
            --source ./
